### ISSUE TITLE
hardware connectors

### ISSUE THREAD

**Issue by jkbeetle** [Lichtwerkstatt/XRTL_SPA#34]
Thinking, Development and Implementation of sustainable connections between ESP32, DriverBoards and Actuators.
Getting rid of dupont cables.

proposal:
- [ ]  design PCB to plug in pcb with integrated connectors to external hardware

**Comment by doomke** [comment]
We currently use the following external hardware components that would need to be accomodated:

1. stepper motors
2. servo motors
3. relais
4. info LEDs

Because the stepper motors have no possibility to check their position it might also be benefitial in the future to have
5. interrupt buttons

This presents an interesting opportunity:
The driver boards for the steppers use simple Darlington arrays, which coincidentaly can also be used to drive relais. We can use this to unify the hardware into a general purpose board offering various connectors for the hardware, for example JST connectors for the stepper motors and screw terminals for the relais.



Proposal:
design PCB with integrated stepper and relais driver curcuits, offering a socket for an ESP32 and a common power terminal for all connected hardware

**Comment by doomke** [comment]
Now available in the [hardware repository](https://github.com/Lichtwerkstatt/XRTL_Hardware/tree/main/PCB):
a general purpose PCB featuring

- a socket for an ESP32 nodeMCU
- 2 connectors for stepper motors
- 2 connectors for servo motors
- 2 relays
- 1 connector for info-LED
