### ISSUE TITLE
Overview Cam Window doesn´t work on smartphone

### ISSUE THREAD

**Issue by FalkoFuroro** [Lichtwerkstatt/XRTL_SPA#99]
The window opens but doesn't show anything.
It works on Office PCs but not on Laptops or Smartphones.

**Comment by doomke** [comment]
Can confirm absence of a camera stream when opened under certain conditions, though the cause is quite elusive.
I tested it with 3 devices:

1.  desktop PC at work
    - connected via local network: ✔
2. smartphone
    - connected via eduroam: ❌
    - connected via home wifi: ✔
    - connected via mobile data: ❌
3. desktop PC at home
    - connected via normal network: ✔
    - connected via VPN: ❌

I think we can conclude that it is certainly network depended, though _not_ whether or not the device is located within the local network. Stressing the point that devices 2 and 3 were operated under identical settings other than the network, I have no clue what is going on here and am open for any suggestions.

**Comment by Claralein** [comment]
Workaround found:

Use an ESP32 based camera, which use the socket.io server to distribute the stream instead of webRTC.
